version: "3.9"

services:

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    platform: linux/arm64
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      # --- REQUIRED for KRaft ---
      CLUSTER_ID: FcZn6E4kQQm3NDREcejxyA

      # --- KRaft mode ---
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # --- Listeners ---
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      # --- Controller quorum ---
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # --- Single-node dev ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    platform: linux/arm64
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT

  postgres:
    image: postgres:16
    platform: linux/arm64
    container_name: postgres
    environment:
      POSTGRES_DB: traffic
      POSTGRES_USER: traffic
      POSTGRES_PASSWORD: traffic
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    platform: linux/arm64
    container_name: redis
    ports:
      - "6379:6379"

  traffic-simulator:
    build:
      context: ../traffic-simulator
      dockerfile: Dockerfile
    container_name: traffic-simulator
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: traffic.raw
      GENERATOR_INTERVAL: 120s
    restart: unless-stopped

volumes:
  postgres-data:
