apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-simulator
  labels:
    {{- include "traffic-system.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.trafficSimulator.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: traffic-simulator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traffic-simulator
    spec:
      containers:
        - name: traffic-simulator
          image: "{{ .Values.global.imageRegistry }}{{ .Values.trafficSimulator.image }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: KAFKA_BROKER
              value: {{ .Values.kafka.bootstrapServers | quote }}
            - name: SCHEMA_REGISTRY_URL
              value: {{ .Values.schemaRegistry.url | quote }}
            {{- range $k, $v := .Values.trafficSimulator.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
